# Generated by Django 5.2.1 on 2025-07-05 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='first_report_uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
