# Generated by Django 5.2.1 on 2025-07-06 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contractors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('expired', 'Contract Expired'), ('imminent', 'Contract Ending Soon'), ('quarterly', 'Contract Ending This Quarter')], max_length=20)),
                ('days_until_end', models.IntegerField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contractors.candidate')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('candidate', 'alert_type')},
            },
        ),
    ]
