# Generated by Django 5.2.4 on 2025-07-25 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
        ('contractors', '0006_rename_candidate_contractor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='candidate',
            new_name='contractor',
        ),
        migrations.AlterUniqueTogether(
            name='alert',
            unique_together={('contractor', 'alert_type')},
        ),
    ]
