# Generated by Django 5.2.1 on 2025-07-06 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor_name', models.CharField(max_length=200)),
                ('client_name', models.CharField(max_length=200)),
                ('contract_start_date', models.DateField()),
                ('contract_end_date', models.DateField()),
                ('weekly_spread_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recruiter_or_account_manager', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('review', 'For Review'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
