# Generated by Django 5.2.4 on 2025-07-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0002_candidate_contractor_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contractor', 'verbose_name_plural': 'Contractors'},
        ),
        migrations.AddField(
            model_name='candidate',
            name='connected_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
