# Generated by Django 5.2.4 on 2025-07-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0003_alter_candidate_options_candidate_connected_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
