# Generated by Django 5.2.4 on 2025-07-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0004_candidate_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='contractor_name',
            new_name='contractor_first_name',
        ),
        migrations.AddField(
            model_name='candidate',
            name='contractor_last_name',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
