# Generated by Django 5.2.4 on 2025-07-25 05:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
        ('contractors', '0005_rename_contractor_name_candidate_contractor_first_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Candidate',
            new_name='Contractor',
        ),
    ]
