# Generated by Django 5.2.4 on 2025-07-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0006_rename_candidate_contractor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='contractor_first_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='contractor_last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
