# Generated by Django 5.2.4 on 2025-07-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0008_alter_contractor_contractor_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='weekly_spread_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Spread'),
        ),
    ]
